
name: Deploy to the Demo SERVER

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "59 23 * * 6"

env:
  AUTHOR: AUTHOR

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: demo

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Push code to the Server
      run: |
        rsync -r --progress --delete ./ ${{ secrets.USER }}@${{ secrets.SERVER }}:/home/${{ secrets.USER }}/subrake
        
    - name: Deploy to the Server
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.SERVER }} "
          cd ./subrake &&
          ls -al &
          ./installer.sh
        "
